name: Deploy to ECR

on:
  push:
    tags-ignore: 
      - 0.*
        
jobs:
 build:
   name: build and publish image
   runs-on: ubuntu-latest

   steps:
   - name: Checkout
     uses: actions/checkout@v2

   - name: Configure AWS credentials from Prodd account
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
       aws-region: $AWS-REGION

   - name: Build and Push image to ECR
     run: |
       $(aws ecr get-login --no-include-email --region $AWS-REGION)
       docker build -t $REPOSITORY_URL:$GITHUB_SHA .
       docker push $REPOSITORY_URL:$GITHUB_SHA
     env:
       REPOSITORY_URL: 905675428251.dkr.ecr.us-east-1.amazonaws.com/github-actions-demo
       AWS-REGION: us-east-1
